apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper-service
  name: zookeeper-service
  namespace: event-streaming-platform
spec:
  ports:
    - name: "port2181"
      port: 2181
      targetPort: 2181
  selector:
    service: zookeeper-service