apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka
  namespace: event-streaming-platform
spec:
  selector:
    service: kafka
  ports:
    - name: "default"
      port: 29092
      targetPort: 29092