apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  #namespace: event-streaming-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kafka-local-storage
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/kafka-pv