apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log-pv
  #namespace: event-streaming-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: zookeeper-log-local-storage
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/zookeeper-log-pv